### ISSUE TITLE
How do we want to render updating tasks?

### ISSUE THREAD

**Issue by Lopez-CL** [Coding-Dojo-Project-Team/Researcher-Village#27]
I'm thinking that our project page also serves as our update task space. I will redesign our page in Balsamiq Cloud to show what I mean. Stand by

**Comment by Teknicl** [comment]
Sounds cool and looking forward to visualizing it.

**Comment by Lopez-CL** [comment]
Okay, finished a [balsamiq prototype](https://balsamiq.cloud/sixsbu9/ptb6xts/rC231) of this. There are actually a few approaches to rendering this. The challenge arises for how much flexibility we want to give users when updating tasks. I will discuss with everyone at tomorrow's meeting.
